-- Migration number: 0006 	 2026-01-14T19:30:00.000Z
-- Migration 0011: Add selected_periods column to proposta_itens
-- Made idempotent to avoid errors if column already exists
-- SQLite doesn't support IF NOT EXISTS for ALTER TABLE ADD COLUMN
-- So we'll use a workaround: try to add it, and if it fails, it's already there
-- This is handled by wrapping in a transaction that we can ignore errors from
-- Check if column exists by trying to select it
-- If this succeeds, column exists; if it fails, we need to add it
-- Since we can't do conditional DDL in SQLite easily, we'll just make this a no-op
-- The column was already added manually, so this migration is now a placeholder
-- No-op migration (column already exists in production)
SELECT 1;
-- Placeholder to make migration valid